import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const alessana = localFont({
  src: "./fonts/Alessana.otf",
  variable: "--font-Alessana",
});
const bebasneue = localFont({
  src: "./fonts/Bebas neue.ttf",
  variable: "--font-bebasneue",
});
const giloryBold = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
  variable: "--font-giloryBold",
});
const giloryregular = localFont({
  src: "./fonts/Gilroy-Regular.ttf",
  variable: "--font-giloryRegular",
});
const gilroySemiBold = localFont({
  src: "./fonts/Gilroy-SemiBold.ttf",
  variable: "--font-gilroySemiBold",
});

const Rockybilly = localFont({
  src: "./fonts/Rockybilly.ttf",
  variable: "--font-Rockybilly",
});

const gilroyMedium = localFont({
  src: "./fonts/Gilroy-Medium.ttf",
  variable: "--font-gilroyMedium",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${alessana.variable} ${bebasneue.variable} ${giloryBold.variable} ${giloryregular.variable} ${gilroySemiBold.variable} ${gilroyMedium.variable} ${Rockybilly.variable}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
